api-version: 2024-02-02-preview
location: {{ .Env.AZURE_LOCATION }}
identity:
  type: UserAssigned
  userAssignedIdentities:
    ? "{{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}"
    : {}
properties:
  environmentId: {{ .Env.AZURE_CONTAINER_APPS_ENVIRONMENT_ID }}
  configuration:
    activeRevisionsMode: single
    runtime:
      dotnet:
        autoConfigureDataProtection: true
    ingress:
      external: false
      targetPort: {{ targetPortOrDefault 8080 }}
      transport: http
      allowInsecure: true
    registries:
      - server: {{ .Env.AZURE_CONTAINER_REGISTRY_ENDPOINT }}
        identity: {{ .Env.AZURE_CONTAINER_REGISTRY_MANAGED_IDENTITY_ID }}
    secrets:
      - name: connectionstrings--app-config
        value: '{{ .Env.APP_CONFIG_APPCONFIGENDPOINT }}'
      - name: connectionstrings--app-secrets
        value: '{{ .Env.APP_SECRETS_VAULTURI }}'
      - name: connectionstrings--asb-messaging
        value: '{{ .Env.ASB_MESSAGING_SERVICEBUSENDPOINT }}'
      - name: connectionstrings--messages-blb
        value: '{{ .Env.MESSAGES_STG_BLOBENDPOINT }}'
      - name: connectionstrings--messages-tbl
        value: '{{ .Env.MESSAGES_STG_TABLEENDPOINT }}'
      - name: connectionstrings--rmq-messaging
        value: amqp://guest:{{ securedParameter "rmq_messaging_password" }}@rmq-messaging:5672
  template:
    containers:
      - image: {{ .Image }}
        name: webapp2
        env:
          - name: AZURE_CLIENT_ID
            value: {{ .Env.MANAGED_IDENTITY_CLIENT_ID }}
          - name: ASPNETCORE_FORWARDEDHEADERS_ENABLED
            value: "true"
          - name: HTTP_PORTS
            value: '{{ targetPortOrDefault 0 }}'
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EVENT_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_EMIT_EXCEPTION_LOG_ATTRIBUTES
            value: "true"
          - name: OTEL_DOTNET_EXPERIMENTAL_OTLP_RETRY
            value: in_memory
          - name: ConnectionStrings__app-config
            secretRef: connectionstrings--app-config
          - name: ConnectionStrings__app-secrets
            secretRef: connectionstrings--app-secrets
          - name: ConnectionStrings__asb-messaging
            secretRef: connectionstrings--asb-messaging
          - name: ConnectionStrings__messages-blb
            secretRef: connectionstrings--messages-blb
          - name: ConnectionStrings__messages-tbl
            secretRef: connectionstrings--messages-tbl
          - name: ConnectionStrings__rmq-messaging
            secretRef: connectionstrings--rmq-messaging
    scale:
      minReplicas: 1
tags:
  azd-service-name: webapp2
  aspire-resource-name: webapp2
